In [1]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    pass

employee1 = Employee("Nitish Harsha", "Somarapu", 85000, "Logistics")
employee2 = Employee("Honey", "Somarapu", 95000, "Finance")

fulltime_employee1 = FulltimeEmployee("Mani", "Somarapu", 65000, "IT")
fulltime_employee2 = FulltimeEmployee("Nitish", "Somarapu", 50000, "HR")

total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)

Average Salary for Employees: 45000.0
Average Salary for Fulltime Employees: 28750.0


In [2]:

import numpy as np
random_vector = np.random.uniform(1, 20, 20)
print("Original Random Vector:\n", random_vector)



Original Random Vector:
 [19.00468002 18.14064836  9.80072193 16.81395338  2.81397501  7.49688788
 16.90877417 13.32295942 18.91797973  6.25019126 14.96043173 10.94287918
 11.96493619 11.02043684  6.88631134 18.56541515  5.65306657 14.94643338
 18.8559866  15.73394807]


In [3]:
reshaped_array = random_vector.reshape(4, 5)
print(reshaped_array)

[[19.00468002 18.14064836  9.80072193 16.81395338  2.81397501]
 [ 7.49688788 16.90877417 13.32295942 18.91797973  6.25019126]
 [14.96043173 10.94287918 11.96493619 11.02043684  6.88631134]
 [18.56541515  5.65306657 14.94643338 18.8559866  15.73394807]]


In [4]:
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0.         18.14064836  9.80072193 16.81395338  2.81397501]
 [ 7.49688788 16.90877417 13.32295942  0.          6.25019126]
 [ 0.         10.94287918 11.96493619 11.02043684  6.88631134]
 [18.56541515  5.65306657 14.94643338  0.         15.73394807]]
